create database data_generator;
create schema repository;
commit;
create table repository.containers
(
    id            bigint generated by default as identity (maxvalue 2147483647)
        constraint containers_pkey
            primary key,
    name          varchar(100) not null,
    creation_date timestamp    not null,
    update_date   timestamp,
    status        varchar(50),
    authenticated boolean,
    type          text,
    cuid          uuid
);
create unique index containers_cuid_uindex
    on repository.containers (cuid);
commit;
create table repository.test_data
(
    id            bigint generated by default as identity
        constraint test_data_pkey
            primary key,
    container_ref bigint not null,
    value         jsonb,
    generator_name text
);
commit;
alter table repository.test_data add constraint test_data_containers_id_fk foreign key (container_ref) references repository.containers;
commit;

